/**
 * Predefined suggestions for tag-based profile fields.
 * Users can still type custom tags – these just accelerate common choices.
 */

export const SKILL_SUGGESTIONS = [
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'Go',
  'Rust',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'React',
  'Angular',
  'Vue.js',
  'Svelte',
  'Node.js',
  'Express.js',
  'Next.js',
  'Django',
  'Flask',
  'Spring Boot',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'Git',
  'SQL',
  'MongoDB',
  'PostgreSQL',
  'Redis',
  'GraphQL',
  'REST APIs',
  'HTML/CSS',
  'Tailwind CSS',
  'Firebase',
  'TensorFlow',
  'PyTorch',
  'Linux',
  'CI/CD',
  'Figma',
  'Unity',
  'R',
  'Scala',
  'Elixir',
  'Terraform',
  'Pandas',
  'NumPy',
];

export const INTEREST_SUGGESTIONS = [
  'Web Development',
  'Machine Learning',
  'AI / LLMs',
  'Data Science',
  'Mobile Development',
  'Cloud Computing',
  'DevOps',
  'Cybersecurity',
  'Game Development',
  'Blockchain',
  'IoT',
  'AR / VR',
  'Robotics',
  'Computer Vision',
  'NLP',
  'Embedded Systems',
  'Systems Programming',
  'Open Source',
  'UI/UX Design',
  'Backend Development',
  'Frontend Development',
  'Full-Stack Development',
  'Database Design',
  'API Design',
  'Microservices',
  'Competitive Programming',
  'Data Engineering',
  'Site Reliability',
  'Quantum Computing',
  'Low-Level / OS',
];
